// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1pnP8HFfqi98tFLiJlKIEkMLSGAeCPI',
    appId: '1:1013724350742:web:5672e4211cbab9ec53a837',
    messagingSenderId: '1013724350742',
    projectId: 'flutter-project-02-96ed2',
    authDomain: 'flutter-project-02-96ed2.firebaseapp.com',
    storageBucket: 'flutter-project-02-96ed2.appspot.com',
    measurementId: 'G-NEB9F7K9LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK8lxvBKCB0-6ax35ZJdWDPyi2tYFEI-o',
    appId: '1:1013724350742:android:0520c68a208ce34a53a837',
    messagingSenderId: '1013724350742',
    projectId: 'flutter-project-02-96ed2',
    storageBucket: 'flutter-project-02-96ed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60EsFUfAcDvN5X2JEVHFOPHy8Fqn1g84',
    appId: '1:1013724350742:ios:cd92dff836d74ef753a837',
    messagingSenderId: '1013724350742',
    projectId: 'flutter-project-02-96ed2',
    storageBucket: 'flutter-project-02-96ed2.appspot.com',
    iosBundleId: 'com.example.tam01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60EsFUfAcDvN5X2JEVHFOPHy8Fqn1g84',
    appId: '1:1013724350742:ios:63d4b5c90bd8535353a837',
    messagingSenderId: '1013724350742',
    projectId: 'flutter-project-02-96ed2',
    storageBucket: 'flutter-project-02-96ed2.appspot.com',
    iosBundleId: 'com.example.tam01.RunnerTests',
  );
}
